import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    commitlint: 'src/commitlint.js',
    'eslint-base': 'src/eslint-base.js',
    'eslint-node': 'src/eslint-node.js',
    'eslint-react': 'src/eslint-react.js',
    'eslint-tsdoc': 'src/eslint-tsdoc.js',
    'eslint-vitest': 'src/eslint-vitest.js',
    index: 'src/eslint-base.js',
    'lint-staged': 'src/lint-staged.js',
    prettier: 'src/prettier.js',
    'semantic-release': 'src/semantic-release.js',
  },
  format: ['cjs', 'esm'],
  outDir: 'dist',
  clean: true,
  splitting: false,
  dts: true,
  sourcemap: false,
  minify: false,
  target: 'es2022',
  platform: 'node',
  treeshake: true,
  external: [
    '@commitlint/config-conventional',
    '@commitlint/types',
    '@eslint/js',
    '@semantic-release/changelog',
    '@semantic-release/commit-analyzer',
    '@semantic-release/git',
    '@semantic-release/github',
    '@semantic-release/npm',
    '@semantic-release/release-notes-generator',
    '@typescript-eslint/eslint-plugin',
    '@typescript-eslint/parser',
    'commitlint',
    'eslint',
    'eslint-config-prettier',
    'eslint-plugin-import',
    'eslint-plugin-jsx-a11y',
    'eslint-plugin-prettier',
    'eslint-plugin-react',
    'eslint-plugin-react-hooks',
    'eslint-plugin-tsdoc',
    'globals',
    'prettier',
    'semantic-release',
    'typescript',
  ],
});
